### ISSUE TITLE
Admin can not edit approvals in model admin (active and completed) OR from pages (workflow log)

### ISSUE THREAD

**Issue by robbieaverill** [symbiote/silverstripe-advancedworkflow#334]
![fix2](https://user-images.githubusercontent.com/5170590/34658594-11e02f0c-f495-11e7-8b58-8bc7244d22c1.png)

My assumption is that clicking on those rows triggers the internal server error alert in the top right of that screenshot.

cc @clarkepaul

**Comment by raissanorth** [comment]
I have looked at this and was able to reproduce the issue (however not able to solve it). As an admin I am able to go into the edit menu for an individual approval job. When I select 'approval' as the next job (poorly phrased), and hit the save button the following happens:

- The workflow status remains 'paused' rather than changing to 'completed'
- I get redirected to the content page, rather than the backlog page
- The content approved by me is not published

**Comment by sachajudd** [comment]
Cool! Thanks for testing @raissanorth happy to close this issue and create a new / edit this issue for an admin not being able to approve paused approvals from your screenshot above 🙂

**Comment by raissanorth** [comment]
Awesome. I think it is a good idea to create a new issue that specifies the issue in more detail. Would you like to do that @sachajudd?
